# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auction_kv_labels_feed.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='auction_kv_labels_feed.proto',
  package='',
  serialized_pb=_b('\n\x1c\x61uction_kv_labels_feed.proto\"\xb7\x01\n\x16\x61uction_kv_labels_feed\x12\x11\n\tdate_time\x18\x01 \x01(\x06\x12\x15\n\rauction_id_64\x18\x02 \x01(\x06\x12\x12\n\nuser_id_64\x18\x03 \x01(\x06\x12\x0b\n\x03key\x18\x04 \x01(\t\x12\r\n\x05value\x18\x05 \x01(\t\x12\x11\n\tkey_label\x18\x06 \x01(\t\x12\x13\n\x0bvalue_label\x18\x07 \x01(\t\x12\x1b\n\x11hashed_user_id_64\x18\x08 \x01(\x0c:\x00\x42&\n$com.appnexus.data.protobuf.generated')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_AUCTION_KV_LABELS_FEED = _descriptor.Descriptor(
  name='auction_kv_labels_feed',
  full_name='auction_kv_labels_feed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date_time', full_name='auction_kv_labels_feed.date_time', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auction_id_64', full_name='auction_kv_labels_feed.auction_id_64', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id_64', full_name='auction_kv_labels_feed.user_id_64', index=2,
      number=3, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='auction_kv_labels_feed.key', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='auction_kv_labels_feed.value', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key_label', full_name='auction_kv_labels_feed.key_label', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value_label', full_name='auction_kv_labels_feed.value_label', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hashed_user_id_64', full_name='auction_kv_labels_feed.hashed_user_id_64', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=True, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=216,
)

DESCRIPTOR.message_types_by_name['auction_kv_labels_feed'] = _AUCTION_KV_LABELS_FEED

auction_kv_labels_feed = _reflection.GeneratedProtocolMessageType('auction_kv_labels_feed', (_message.Message,), dict(
  DESCRIPTOR = _AUCTION_KV_LABELS_FEED,
  __module__ = 'auction_kv_labels_feed_pb2'
  # @@protoc_insertion_point(class_scope:auction_kv_labels_feed)
  ))
_sym_db.RegisterMessage(auction_kv_labels_feed)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$com.appnexus.data.protobuf.generated'))
# @@protoc_insertion_point(module_scope)
