# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: custom_data_feed.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='custom_data_feed.proto',
  package='',
  serialized_pb=_b('\n\x16\x63ustom_data_feed.proto\"k\n\x10\x63ustom_data_feed\x12\x11\n\tdate_time\x18\x01 \x01(\x06\x12\x15\n\rauction_id_64\x18\x02 \x01(\x06\x12\x18\n\x10seller_member_id\x18\x03 \x01(\x05\x12\x13\n\x0bquerystring\x18\x04 \x01(\tB&\n$com.appnexus.data.protobuf.generated')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CUSTOM_DATA_FEED = _descriptor.Descriptor(
  name='custom_data_feed',
  full_name='custom_data_feed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date_time', full_name='custom_data_feed.date_time', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auction_id_64', full_name='custom_data_feed.auction_id_64', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seller_member_id', full_name='custom_data_feed.seller_member_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='querystring', full_name='custom_data_feed.querystring', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=133,
)

DESCRIPTOR.message_types_by_name['custom_data_feed'] = _CUSTOM_DATA_FEED

custom_data_feed = _reflection.GeneratedProtocolMessageType('custom_data_feed', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOM_DATA_FEED,
  __module__ = 'custom_data_feed_pb2'
  # @@protoc_insertion_point(class_scope:custom_data_feed)
  ))
_sym_db.RegisterMessage(custom_data_feed)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$com.appnexus.data.protobuf.generated'))
# @@protoc_insertion_point(module_scope)
