# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: includes/segment_key_value.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='includes/segment_key_value.proto',
  package='',
  serialized_pb=_b('\n includes/segment_key_value.proto\"U\n\x11segment_key_value\x12\x12\n\nsegment_id\x18\x01 \x01(\x05\x12\x15\n\rsegment_value\x18\x02 \x01(\x05\x12\x15\n\rlast_seen_min\x18\x03 \x01(\x05\x42&\n$com.appnexus.data.protobuf.generated')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SEGMENT_KEY_VALUE = _descriptor.Descriptor(
  name='segment_key_value',
  full_name='segment_key_value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='segment_id', full_name='segment_key_value.segment_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='segment_value', full_name='segment_key_value.segment_value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_seen_min', full_name='segment_key_value.last_seen_min', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['segment_key_value'] = _SEGMENT_KEY_VALUE

segment_key_value = _reflection.GeneratedProtocolMessageType('segment_key_value', (_message.Message,), dict(
  DESCRIPTOR = _SEGMENT_KEY_VALUE,
  __module__ = 'includes.segment_key_value_pb2'
  # @@protoc_insertion_point(class_scope:segment_key_value)
  ))
_sym_db.RegisterMessage(segment_key_value)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$com.appnexus.data.protobuf.generated'))
# @@protoc_insertion_point(module_scope)
